// <auto-generated />
using System;
using DataBaseStudentUIR.DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBaseStudentUIR.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataBaseStudentUIR.Models.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CIN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodeUIR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f76cb5d7-22a5-4a8f-8c05-3dc1f57faffa"),
                            Address = "321 Maple St, Kentira",
                            BirthDate = new DateTime(1995, 7, 12, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            CIN = "GSI451479",
                            CodeUIR = "UIR5547",
                            Email = "souhail@jobintech-uir.ma",
                            FirstName = "Souhail",
                            Gender = "Male",
                            LastName = "Alaoui",
                            Password = "123456",
                            Phone = "+212645678901"
                        },
                        new
                        {
                            Id = new Guid("f76cb5d7-22a5-5a8f-8c05-3dc1f57faffa"),
                            Address = "321 Maple St, Kentira",
                            BirthDate = new DateTime(1995, 7, 12, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            CIN = "GSI451479",
                            CodeUIR = "UIR56477",
                            Email = "adam@jobintech-uir.ma",
                            FirstName = "Adam",
                            Gender = "Male",
                            LastName = "Alaoui",
                            Password = "123456",
                            Phone = "+212645678901"
                        },
                        new
                        {
                            Id = new Guid("f76cb5d7-22a5-4a8f-8c05-3dc1f57faffb"),
                            Address = "321 Maple St, Agadir",
                            BirthDate = new DateTime(1995, 7, 12, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            CIN = "GHI456789",
                            CodeUIR = "UIR005",
                            Email = "sara.brahimi@jobintech-uir.ma",
                            FirstName = "Sara",
                            Gender = "Female",
                            LastName = "Brahimi",
                            Password = "password123",
                            Phone = "+212645678901"
                        },
                        new
                        {
                            Id = new Guid("f76cb5d7-82a5-4a8f-8c05-3dc1f57faffe"),
                            Address = "321 Maple St, Kentira",
                            BirthDate = new DateTime(1995, 7, 12, 9, 20, 0, 0, DateTimeKind.Unspecified),
                            CIN = "GSI451479",
                            CodeUIR = "UIR57412",
                            Email = "ayoub@jobintech-uir.ma",
                            FirstName = "Ayoub",
                            Gender = "Male",
                            LastName = "Grami",
                            Password = "123456",
                            Phone = "+212645678901"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
